//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRequest
    {
        public int ClassRequestId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> ClassDetailId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Student Student { get; set; }
    }
}
