//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDetailSlot
    {
        public int ClassDetailSlotId { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> ClassDetailId { get; set; }
    
        public virtual ClassDetail ClassDetail { get; set; }
    }
}
