//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AccountStudents = new HashSet<AccountStudent>();
            this.ClassDetailStudents = new HashSet<ClassDetailStudent>();
            this.ClassRequests = new HashSet<ClassRequest>();
        }
    
        public int StudentID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string Name { get; set; }
        public string ParrentPhone { get; set; }
        public Nullable<System.DateTime> StartingDay { get; set; }
        public string StudentPhone { get; set; }
        public Nullable<int> TuitionFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountStudent> AccountStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassDetailStudent> ClassDetailStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRequest> ClassRequests { get; set; }
    }
}
